// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Aoe(Props) {
  return React.createElement("div", undefined, "hola");
}

var make = Aoe;

export {
  make ,
  
}
/* react Not a pure module */
