// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Board$RescriptReactIntro from "./Board.bs.js";

import './App.css'
;

function App(Props) {
  return React.createElement("div", {
              className: "game"
            }, React.createElement("div", {
                  className: "game-board"
                }, React.createElement(Board$RescriptReactIntro.make, {})), React.createElement("div", {
                  className: "game-info"
                }, React.createElement("div", undefined), React.createElement("ol", undefined)));
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
