// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as Square$RescriptReactIntro from "./Square.bs.js";

import './Board.css'
;

function Board(Props) {
  var renderSquare = function (i) {
    return React.createElement(Square$RescriptReactIntro.make, {
                value: i
              });
  };
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "status"
                }, "Next player: X"), React.createElement("div", {
                  className: "board-row"
                }, Belt_Array.map([
                      1,
                      2,
                      3
                    ], renderSquare)), React.createElement("div", {
                  className: "board-row"
                }, renderSquare(4), renderSquare(5), renderSquare(6)), React.createElement("div", {
                  className: "board-row"
                }, React.createElement(Square$RescriptReactIntro.make, {
                      value: 7
                    }), React.createElement(Square$RescriptReactIntro.make, {
                      value: 8
                    }), React.createElement(Square$RescriptReactIntro.make, {
                      value: 9
                    })));
}

var make = Board;

export {
  make ,
  
}
/*  Not a pure module */
