// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import './Square.css'
;

function Square(Props) {
  return React.createElement("button", {
              className: "square"
            });
}

var make = Square;

export {
  make ,
  
}
/*  Not a pure module */
