// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

import './Square.css'
;

function Square(Props) {
  var value = Props.value;
  var match = React.useState(function () {
        return "";
      });
  var setText = match[1];
  return React.createElement("button", {
              className: "square",
              onClick: (function (evt) {
                  evt.preventDefault();
                  return Curry._1(setText, (function (prev) {
                                if (prev === "X") {
                                  return "Y";
                                } else {
                                  return "X";
                                }
                              }));
                })
            }, value, match[0]);
}

var make = Square;

export {
  make ,
  
}
/*  Not a pure module */
